import { KeyboardData } from "./data";

export const qwerty: KeyboardData = {
    name: "QWERTY",
    script: "latin",
    rows: [
        {
            height: 1,
            shift: 0,
            keys: [
                {
                    width: 1,
                    shift: 0,
                    c: "q",
                    nw: "",
                    ne: "1",
                    sw: "",
                    se: "esc",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "w",
                    nw: "~",
                    ne: "2",
                    sw: "@",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "e",
                    nw: "!",
                    ne: "3",
                    sw: "#",
                    se: "loc €",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "r",
                    nw: "loc ₪",
                    ne: "4",
                    sw: "$",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "t",
                    nw: "",
                    ne: "5",
                    sw: "%",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "y",
                    nw: "",
                    ne: "6",
                    sw: "^",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "u",
                    nw: "",
                    ne: "7",
                    sw: "&",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "i",
                    nw: "",
                    ne: "8",
                    sw: "*",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "o",
                    nw: "loc accent_macron",
                    ne: "9",
                    sw: "(",
                    se: ")",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "p",
                    nw: "",
                    ne: "0",
                    sw: "f11_placeholder",
                    se: "f12_placeholder",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
            ],
        },
        {
            height: 1,
            shift: 0,
            keys: [
                {
                    width: 1,
                    shift: 0.5,
                    c: "a",
                    nw: "tab",
                    ne: "`",
                    sw: "",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "s",
                    nw: "loc accent_ring",
                    ne: "",
                    sw: "loc ß",
                    se: "loc accent_ogonek",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "d",
                    nw: "loc accent_grave",
                    ne: "loc £",
                    sw: "loc accent_aigu",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "f",
                    nw: "loc accent_dot_above",
                    ne: "",
                    sw: "",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "g",
                    nw: "loc accent_caron",
                    ne: "-",
                    sw: "_",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "h",
                    nw: "",
                    ne: "=",
                    sw: "+",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "j",
                    nw: "loc accent_trema",
                    ne: "loc accent_circonflexe",
                    sw: "{",
                    se: "}",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "k",
                    nw: "loc accent_double_aigu",
                    ne: "",
                    sw: "[",
                    se: "]",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "l",
                    nw: "",
                    ne: "|",
                    sw: "\\",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
            ],
        },
        {
            height: 1,
            shift: 0,
            keys: [
                {
                    width: 1.5,
                    shift: 0,
                    c: "shift",
                    nw: "",
                    ne: "loc capslock",
                    sw: "",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "z",
                    nw: "",
                    ne: "",
                    sw: "",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "x",
                    nw: "",
                    ne: "",
                    sw: "",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "c",
                    nw: "loc accent_cedille",
                    ne: "<",
                    sw: ".",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "v",
                    nw: "",
                    ne: ">",
                    sw: ",",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "b",
                    nw: "",
                    ne: "?",
                    sw: "/",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "n",
                    nw: "loc accent_tilde",
                    ne: ":",
                    sw: ";",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    c: "m",
                    nw: "",
                    ne: '"',
                    sw: "'",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
                {
                    width: 1.5,
                    shift: 0,
                    c: "backspace",
                    nw: "",
                    ne: "delete",
                    sw: "",
                    se: "",
                    w: "",
                    e: "",
                    n: "",
                    s: "",
                    slider: false,
                },
            ],
        },
    ],
    bottomRow: true,
};

export const keyboards: Record<string, KeyboardData> = {
    Blank: { name: "Custom Layout", script: "", bottomRow: true, rows: [] },
    QWERTY: qwerty,
};
